const orchids = [
  {
    id: "1",
    name: "Taichung Beauty",
    rating: 5,
    isSpecial: true,
    isNatural: false,
    image: "/img/o1.jpg",
    color: "Pink",
    numberOfLike: 192,
    origin: "Taiwan",
    category: "Cattleya",
    detail:
      "A famous hybrid from Taiwan with large, thick petals in vivid pink. Often showcased in exhibitions and festive decorations.",
    videoUrl: "https://www.youtube.com/embed/bhOEYjiBb7o?si=LuvXb4U0fcHRULk2",
  },
  {
    id: "2",
    name: "Phalaenopsis Sogo Yukidian",
    rating: 4.5,
    isSpecial: false,
    isNatural: true,
    image: "/img/o2.jpg",
    color: "White",
    numberOfLike: 210,
    origin: "Japan",
    category: "Phalaenopsis",
    detail:
      "Known as the “Japanese White Moth Orchid,” its blooms can last for months. A symbol of elegance and purity.",
    videoUrl: "https://www.youtube.com/embed/Q5EGN-zyxBQ?si=LOhnkYtWIXu2OfJZ",
  },
  {
    id: "3",
    name: "Dendrobium Nobile",
    rating: 4,
    isSpecial: true,
    isNatural: true,
    image: "/img/o3.jpg",
    color: "Pink",
    numberOfLike: 175,
    origin: "India",
    category: "Dendrobium",
    detail:
      "A medicinally valued orchid with purple-white flowers and sweet fragrance. Typically blooms in spring.",
    videoUrl: "https://www.youtube.com/embed/xcNaWfesj8M?si=p3f0_3vDP6GLEO-j",
  },
  {
    id: "4",
    name: "Vanda Pachara Delight",
    rating: 5,
    isSpecial: true,
    isNatural: false,
    image: "/img/o4.jpg",
    color: "Purple",
    numberOfLike: 220,
    origin: "Thailand",
    category: "Vanda",
    detail:
      "Nicknamed the “Blue Queen” among orchids, with thick petals and rare, striking blue blossoms. A star at international shows.",
    videoUrl: "https://www.youtube.com/embed/zZy_m26gnJU?si=8ciLkilaAkrrxCXu",
  },
  {
    id: "5",
    name: "Cymbidium Golden Elf",
    rating: 4.2,
    isSpecial: false,
    isNatural: true,
    image: "/img/o5.jpg",
    color: "Yellow",
    numberOfLike: 160,
    origin: "Australia",
    category: "Cymbidium",
    detail:
      "Bright golden-yellow flowers that bloom in clusters. Easy to grow and a popular gift choice.",
    videoUrl: "https://www.youtube.com/embed/RdmgdjULNdQ?si=TeVnP7JVeWU9c6wf",
  },
  {
    id: "6",
    name: "Miltonia Sunset",
    rating: 4.8,
    isSpecial: true,
    isNatural: false,
    image: "/img/o6.jpg",
    color: "Yellow and Pink",
    numberOfLike: 130,
    origin: "Brazil",
    category: "Miltonia",
    detail:
      "A hybrid with fiery orange blooms resembling a sunset. Known for its mild fragrance and decorative value.",
    videoUrl: "https://www.youtube.com/embed/mYwJQsw9w_U?si=ZZnK4UbOnax0R7T5",
  },
  {
    id: "7",
    name: "Paphiopedilum Maudiae",
    rating: 4.6,
    isSpecial: false,
    isNatural: true,
    image: "/img/o7.jpg",
    color: "White and Green",
    numberOfLike: 145,
    origin: "Vietnam",
    category: "Paphiopedilum",
    detail:
      "A slipper orchid with green mottled leaves and striking pouch-shaped flowers. Appreciated for its exotic look.",
    videoUrl: "https://www.youtube.com/embed/l6yWRZG5_us?si=VXRIfsi1fdHzptyk",
  },
  {
    id: "8",
    name: "Oncidium Sharry Baby",
    rating: 4.9,
    isSpecial: true,
    isNatural: false,
    image: "/img/o8.jpg",
    color: "Red",
    numberOfLike: 200,
    origin: "Ecuador",
    category: "Oncidium",
    detail:
      "Famously nicknamed the “Chocolate Orchid” for its sweet cocoa-like fragrance. Produces clusters of small red blossoms.",
    videoUrl: "https://www.youtube.com/embed/7xNNdnaUmYU?si=B-8W8MFzaEfyQl_r",
  },
  {
    id: "9",
    name: "Brassia Rex",
    rating: 4.3,
    isSpecial: false,
    isNatural: true,
    image: "/img/o9.jpg",
    color: "Brown",
    numberOfLike: 110,
    origin: "Mexico",
    category: "Brassia",
    detail:
      "Also called the “Spider Orchid” due to its long, narrow petals. Adds a dramatic touch to any orchid collection.",
    videoUrl: "https://www.youtube.com/embed/vQTU_J71mNw?si=HMo5CNKvzGruepcn",
  },
  {
    id: "10",
    name: "Cattleya Walkeriana",
    rating: 5,
    isSpecial: true,
    isNatural: true,
    image: "/img/o10.jpg",
    color: "Pink",
    numberOfLike: 250,
    origin: "Brazil",
    category: "Cattleya",
    detail:
      "One of Brazil’s iconic orchids, famous for its strong fragrance and bright pink blossoms. Often used in breeding programs.",
    videoUrl: "https://www.youtube.com/embed/WszJgoUxBuI?si=fxMUd8OTcKNdwfo_",
  },
  {
    id: "11",
    name: "Epidendrum Radicans",
    rating: 4.1,
    isSpecial: false,
    isNatural: true,
    image: "/img/o11.jpg",
    color: "Orange",
    numberOfLike: 90,
    origin: "Colombia",
    category: "Epidendrum",
    detail:
      "A hardy orchid with clusters of bright orange flowers. Known for blooming almost year-round in warm climates.",
    videoUrl: "https://www.youtube.com/embed/BU9eUQudhlg?si=LxkuVeVQAgE9-svN",
  },
  {
    id: "12",
    name: "Lycaste Aromatica",
    rating: 4.7,
    isSpecial: true,
    isNatural: false,
    image: "/img/o12.jpg",
    color: "Yellow",
    numberOfLike: 170,
    origin: "Guatemala",
    category: "Lycaste",
    detail:
      "Highly fragrant yellow blooms with a citrus-like scent. Often used in hybridization and admired for its perfume.",
    videoUrl: "https://www.youtube.com/embed/QOCQ-08mE_U?si=A7tIDe5Obd6EXfPl",
  },
  {
    id: "13",
    name: "Masdevallia Veitchiana",
    rating: 4.4,
    isSpecial: false,
    isNatural: true,
    image: "/img/o13.jpg",
    color: "Red",
    numberOfLike: 80,
    origin: "Peru",
    category: "Masdevallia",
    detail:
      "Known as the “King of Masdevallias,” with brilliant orange-red blooms. Native to the Andes and thrives in cool climates.",
    videoUrl: "https://www.youtube.com/embed/kaPgM8tkwMo?si=EUY91aLYQMOjIVYn",
  },
  {
    id: "14",
    name: "Bulbophyllum Medusae",
    rating: 4.5,
    isSpecial: true,
    isNatural: false,
    image: "/img/o14.jpg",
    color: "White",
    numberOfLike: 60,
    origin: "Malaysia",
    category: "Bulbophyllum",
    detail:
      "Features unusual white flower clusters with long, hair-like petals resembling Medusa’s snakes. A true collector’s gem.",
    videoUrl: "https://www.youtube.com/embed/eQBC7ZwoBKY?si=Hb9vlHdWFgjVeKsj",
  },
  {
    id: "15",
    name: "Coelogyne Cristata",
    rating: 4.2,
    isSpecial: false,
    isNatural: true,
    image: "/img/o15.jpg",
    color: "White",
    numberOfLike: 100,
    origin: "Nepal",
    category: "Coelogyne",
    detail:
      "Elegant white blooms with yellow throats. Often called the “Crested Coelogyne,” it symbolizes purity in Himalayan culture.",
    videoUrl: "https://www.youtube.com/embed/wrYd3b_HZQs?si=6jQs2hyEseXz4Jyu",
  },
  {
    id: "16",
    name: "Laelia Anceps",
    rating: 4.9,
    isSpecial: true,
    isNatural: false,
    image: "/img/o16.jpg",
    color: "Pink",
    numberOfLike: 140,
    origin: "Mexico",
    category: "Laelia",
    detail:
      "A resilient species from Mexico, producing vibrant purple flowers on tall spikes. Popular in winter orchid shows.",
    videoUrl: "https://www.youtube.com/embed/gxaYpmPTgA4?si=CZW0JltrN6oCaCfv",
  },
];

export default orchids;
